### ISSUE TITLE
上傳視頻后閃退

### ISSUE THREAD

**Issue by Zpoorguy** [JakeVander/YOLOv5-Intrusion-Detection-System#3]
Traceback (most recent call last):
  File "detect_logicwd.py", line 468, in show_video_frame
    info_show = self.detect(name_list, img)
  File "detect_logicwd.py", line 246, in detect
    pred = self.model(img, augment=self.opt.augment)[0]
  File "C:\Users\28906\PycharmProjects\PythonProject\.venv\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\28906\PycharmProjects\PythonProject\YOLOv5-Intrusion-Detection-System\models\yolo.py", line 123, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "C:\Users\28906\PycharmProjects\PythonProject\YOLOv5-Intrusion-Detection-System\models\yolo.py", line 139, in forward_once
    x = m(x)  # run
  File "C:\Users\28906\PycharmProjects\PythonProject\.venv\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\28906\PycharmProjects\PythonProject\YOLOv5-Intrusion-Detection-System\models\yolo.py", line 55, in forward
    y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
RuntimeError: The size of tensor a (80) must match the size of tensor b (56) at non-singleton dimension 3

請問這個問題要怎樣解決，謝謝

**Comment by jaycheney** [comment]
Check this link https://github.com/ultralytics/yolov5/issues/3809
